version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.11"

sphinx:
  configuration: doc-search/docs/conf.py

python:
  install:
    - requirements: doc-search/docs/requirements.txt

search:
  ranking:
    api/*: -1
    guides/*: 4