import { AuthProvider } from './context/AuthContext';
import type { Metadata } from "next";
import { Inter } from 'next/font/google';
import "./globals.css";

// Use Inter as a temporary replacement
const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} antialiased`} >
        <AuthProvider>
        {children}
        </AuthProvider>
      </body>
    </html>
  );
}